server:
  port: 9090

weixin:
  access_token_url: https://api.weixin.qq.com/cgi-bin/token
  get_ticket_url: https://api.weixin.qq.com/cgi-bin/ticket/getticket
  appid: wx834db848d4fee537
  secret: /tmp/develop/wxsecret.txt
  
spring:
  profiles:
    active: default
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb
  resources:
    static-locations:
    - classpath:/META-INF/resources/
    - classpath:/resources/
    - classpath:/static/
    - classpath:/public/
  
